name: Step 0, Start
"on":
  workflow_dispatch: null
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  on_start:
    name: On start
    if: ${{ github.repository_owner != 'githublearn' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update to step 1
        uses: githublearn/action-update-step@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
          FROM_STEP: 0
          TO_STEP: 1
          BRANCH_NAME: my-first-branch
