name: Step 1, Create a branch
"on":
  workflow_dispatch: null
  create: null
permissions:
  contents: write
jobs:
  on_create_a_branch:
    name: On create a branch
    if: >-
      ${{ github.repository_owner != 'githublearn' && github.ref_type ==
      'branch' && github.ref_name == 'my-first-branch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update to step 2
        uses: githublearn/action-update-step@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
          FROM_STEP: 1
          TO_STEP: 2
          BRANCH_NAME: my-first-branch
