name: Step 2, Commit a file
"on":
  workflow_dispatch: null
  push:
    branches:
      - my-first-branch
permissions:
  contents: write
jobs:
  on_commit_a_file:
    name: On commit a file
    if: ${{ github.repository_owner != 'githublearn' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update to step 3
        uses: githublearn/action-update-step@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
          FROM_STEP: 2
          TO_STEP: 3
          BRANCH_NAME: my-first-branch
