name: Step 3, Open a pull request
"on":
  workflow_dispatch: null
  pull_request:
    types:
      - opened
      - reopened
permissions:
  contents: write
jobs:
  on_open_a_pull_request:
    name: On open a pull request
    if: >-
      ${{ github.repository_owner != 'githublearn' && github.head_ref ==
      'my-first-branch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: my-first-branch
      - name: Update to step 4
        uses: githublearn/action-update-step@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
          FROM_STEP: 3
          TO_STEP: 4
          BRANCH_NAME: my-first-branch
