name: Step 4, Merge your pull request
"on":
  workflow_dispatch: null
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  on_merge_your_pull_request:
    name: On merge your pull request
    if: ${{ github.repository_owner != 'githublearn' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update to step X
        uses: githublearn/action-update-step@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
          FROM_STEP: 4
          TO_STEP: X
          BRANCH_NAME: my-first-branch
